### ISSUE TITLE
Transition data storage format from .docx to .txt for LLM

### ISSUE THREAD

**Issue by alik-r** [ZetyByte/ufaz-chatbot#16]
Currently, the language model stores its data in .docx file format, and during every model load, we parse this data. However, since rich text support is not needed in our case, .txt files offer a more lightweight and easily parsable alternative.

**Comment by Pavel418** [comment]
I was thinking about loading data and a few other modules only once, during server's start-up, then reuse them to save memory and processing power. 
I think it would not affect the performance much in this case, yet editing .docx files is way easier than .txt. I have also read that it is possible to use file structure during its division into chunks, maybe we can use it in the future. 
If there are no other reason for changing it, I suggest to leave the files in .docx format.
